# Generated by Django 2.2.7 on 2019-11-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1256)),
                ('Price', models.IntegerField(default=0)),
                ('ImageUrl', models.CharField(max_length=1256)),
            ],
        ),
    ]
